# BUILD-USING:        docker build -t data .
# RUN-USING:          docker run --name DATA data
FROM          busybox
VOLUME        ["/var/docker/log", "/var/docker/mongod"]
CMD           ["/bin/true"]
